### Reset Database (Start)
POST http://localhost:8080/admin/reset

### Create User
# @name create_user
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "saul@bettercall.com"
}

### Create Chirp
@user_id = {{create_user.response.body.id}}

POST http://localhost:8080/api/chirps
Content-Type: application/json

{
  "body": "If you're committed enough, you can make any story work.",
  "user_id": "{{user_id}}"
}

### Get all chrips
GET http://localhost:8080/api/chirps
Content-Type: application/json


### Reset Database (Clean Up)
POST http://localhost:8080/admin/reset
